name: Actuality Revisited
favicon: null
layout_spectrum: 0.7899274034425616
typography_spectrum: 0.44845350831747055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6004721466451883
  lightness: 0.486907230457291
  saturation: 0.8405796871520579
  rhythmicContrast: 0.7223259243182838
purpose: []
